### ISSUE TITLE
[新主页] 缝合怪主页

### ISSUE THREAD

**Issue by Ext1nguisher** [MFn233/PCL-Mainpage-Market#10]
**名称**
缝合怪主页

**简介**
配色激进、相对美观

**直链**
https://ext1nguisher.github.io/Custom.xaml

**适用于构建器的自定义文本**
```
缝合怪主页
[链接](https://ext1nguisher.github.io/Custom.xaml)
::disc
简约、实用、美观
::enddisc
```

**Comment by JingHai-Lingyun** [comment]
缝合怪主页是什么……
@MFn233

**Comment by MFn233** [comment]
@JingHai-Lingyun 
我不理解，可能是没想好名字
打算叫他“Ext1nguisher的主页”
