### ISSUE TITLE
[新主页] MagicBox PCL Mainpage

### ISSUE THREAD

**Issue by FutureStudios-FSC** [MFn233/PCL-Mainpage-Market#9]
**名称**
Magic Box PCL Mainpage（魔法主页）

**简介**
FSC制作的第一个PCL主页，
偶尔看到自定义主页之后做的。
 _感谢 Github@MFn233_

**直链**
http://xxag.top/FSC%20Statics/Misc/MagicBox.xaml （这是最新）
https://cdn.jsdelivr.net/gh/FutureStudios-FSC/PCL-Mainpage-MagicBox@main/MagicBox.xaml

**适用于构建器的自定义文本**
```
Magic Box PCL Mainpage
http://xxag.top/FSC%20Statics/Misc/MagicBox.xaml
::disc
FSC制作的第一个PCL主页，
偶尔看到自定义主页之后做的。
感谢 Github@MFn233
::enddisc
```

**Comment by MFn233** [comment]
支持多个链接的

**Comment by MFn233** [comment]
支持多个链接的

**Comment by FutureStudios-FSC** [comment]
改完了

`Magic Box PCL Mainpage
::link
http://xxag.top/FSC%20Statics/Misc/MagicBox.xaml
https://cdn.jsdelivr.net/gh/FutureStudios-FSC/PCL-Mainpage-MagicBox@main/MagicBox.xaml
::endlink
::disc
FSC制作的第一个PCL主页，
偶尔看到自定义主页之后做的。
感谢 Github@MFn233
::enddisc`

**Comment by FutureStudios-FSC** [comment]
麻烦换一下行...

**Comment by MFn233** [comment]
有空我会加入的，现在忙对不起：（

**Comment by FutureStudios-FSC** [comment]
**好的谢谢**

**Comment by FutureStudios-FSC** [comment]
我还搞了个预览功能...麻烦放一下grid
```
<local:MyIconTextButton Margin="0,4,0,8" Height="35" HorizontalAlignment="Center"
            Text="预览主页" EventType="打开帮助" EventData="http://xxag.top/FSC Statics/Misc/MagicBox.json"
            LogoScale="1.02" Logo="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
```

**Comment by JingHai-Lingyun** [comment]
建议是使用 `%20` 代替 Url 中的 ` `

**Comment by MFn233** [comment]
> 我还搞了个预览功能...麻烦放一下grid
> 
> ```
> <local:MyIconTextButton Margin="0,4,0,8" Height="35" HorizontalAlignment="Center"
>             Text="预览主页" EventType="打开帮助" EventData="http://xxag.top/FSC Statics/Misc/MagicBox.json"
>             LogoScale="1.02" Logo="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
> ```

emm我日后想换个语言做这个构建器了
太难用
正好你这个加入应该可以

**Comment by MFn233** [comment]
好的，已经加入！
